* Contents                                                              :TOC:
 - [[#installation][Installation]]
 - [[#usage][Usage]]
 - [[#license][License]]

* Installation
Available via Clojars. Project badge coming soon!

* Usage
#+begin_src clojure
  (ns app.foo-bar-test
    (:require [app.foo-bar :as sut]
              [clojure.test :refer :all]
              [invetica.test.spec :as test.spec]))

  (use-fixtures :once test.spec/instrument)

  (deftest t-specs
    (test.spec/is-well-specified 'app.foo-bar))
#+end_src

* License
The MIT License (MIT)

Copyright © 2017 Invetica Ltd

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
